### ISSUE TITLE
lts的cpu、内存监控问题

### ISSUE THREAD

**Issue by ztajy** [ltsopensource/light-task-scheduler#238]
昨天在windowns环境做1.6.5版本测试时，发现控制台打印了很多cpu超过90%的日志，tasktracker就暂停从jobtracker拉任务了，导致任务不执行，但同时在资源管理器中看cpu利用率，并没有超过90%，请问这是咋回事，或者cpu、内存等的监控是否可以手动配置开启与否，谢谢。
![image](https://cloud.githubusercontent.com/assets/3434060/14036725/f330a69e-f276-11e5-85f6-ced26898462c.png)

**Comment by qq254963746** [comment]
这个我稍后check下，可以关闭的， lb.machine.res.check.enable 这个参数设置成 false, 
TaskTracker.addConfig("lb.machine.res.check.enable", "false")

**Comment by ztajy** [comment]
ok tks！
