### ISSUE TITLE
有关于Cron表达式的问题

### ISSUE THREAD

**Issue by yangfeiran** [ltsopensource/light-task-scheduler#308]
您好，

我看到可以手动写Cron表达式，而不使用前端的点击插件进行Cron表达式构造。但是感觉和Cron4j的表达式定义不一样啊，看了下源码里面，一共支持7个位置的定义，cron4j支持5个位置。除了这个以外：                  
    protected static final int SECOND = 0;
    protected static final int MINUTE = 1;
    protected static final int HOUR = 2;
    protected static final int DAY_OF_MONTH = 3;
    protected static final int MONTH = 4;
    protected static final int DAY_OF_WEEK = 5;
    protected static final int YEAR = 6;
请问各个位置的要求是什么啊？
每个位置都要填写么？

**Comment by qq254963746** [comment]
这个CronExpression 是取自 quartz 中的, 可以在网上找找文档看看
