### ISSUE TITLE
lts-admin.cfg 的jobT配置无效

### ISSUE THREAD

**Issue by zhouxianjun** [ltsopensource/light-task-scheduler#316]
RT：lts-admin.cfg 的 jobT.job.logger 配置无效
![mz 1eg4 3_o1qa xpisdo 1](https://cloud.githubusercontent.com/assets/5254523/20391073/b13326d0-ad0c-11e6-9251-c04d4020eace.png)

![j_iltbw 7i1x e jyz f](https://cloud.githubusercontent.com/assets/5254523/20391096/d5dbf962-ad0c-11e6-879f-e255e06143ff.png)

蓝色不加上就无效。导致 我在admin 扩展的SPI无效

**Comment by qq254963746** [comment]
在lts-admin 中，用不到JobTracker的这个jobLogger , 只有在JobTracker的中才用到这个, 这里lts-admin 只访问JobQueue

**Comment by zhouxianjun** [comment]
额。。。在lts-admin中的任务日志查看就需要。。。

**Comment by zhouxianjun** [comment]
譬如加个性化查询或者返回数据格式化之类的

**Comment by qq254963746** [comment]
嗯，你bugfix下，提交个 pull request

**Comment by qq254963746** [comment]
我review下就可以了

**Comment by qq254963746** [comment]
你直接配置成job.logger=xxx吧，不用改代码

**Comment by zhouxianjun** [comment]
ok,thx 需要设置成: configs.job.logger=xxx
