### ISSUE TITLE
replaceOnExist参数

### ISSUE THREAD

**Issue by zyl0622** [ltsopensource/light-task-scheduler#339]
如果多实例中每个实例都有任务，replaceOnExist=true是不是意味着任务只有一个实例的任务会执行；反之，如果是false，就是每个实例的任务都会执行一次？

**Comment by qq254963746** [comment]
replaceOnExist表示提交的时候，如果该任务已经在队列中了，为true时就替换掉，如果为false 就会丢弃当前提交的
