### ISSUE TITLE
任务调度中的实时任务的疑问

### ISSUE THREAD

**Issue by xchz** [ltsopensource/light-task-scheduler#351]
看了[和其他解决方案的比较](https://qq254963746.gitbooks.io/lts/content/introduce/compareother.html)，让我对LTS任务调度的使用场景有了更清晰的认识，非常感谢。在分析实时任务的段落，提到:
```
JobClient 相当于 MQ 的 Producer , JobTracker 相当于 MQ 的 Broker , TaskTracker 相当于 MQ 的 Consumer
```
我也觉得这里和mq很像，但是在Consumer这里我有点疑问，rabbitmq中的consumer是跟queue关联的，而不同的queue是对不同类型的消息感兴趣的，所以关联到不同queue的consumer消费的消息是不同类型的，也就是rabbitmq中的[topic](http://www.rabbitmq.com/tutorials/tutorial-five-python.html)，那么LTS任务调度中对这样的使用场景是否能支持呢？文档中对这个没有涉及，所以提了issue。

**Comment by zhaoyuguang** [comment]
实现为多个队列 分组调用？

**Comment by zhaoyuguang** [comment]
可以起两个task集群消费不同的shareField

**Comment by xchz** [comment]
3q
