### ISSUE TITLE
tracker 日志过大占满磁盘, 有没有自动清理机制

### ISSUE THREAD

**Issue by iamhaley** [ltsopensource/light-task-scheduler#410]
目前我们生产LTS使用mysql存储，但是任务数量、频率大，导致磁盘会很快写满(2周吧)
目前有从运维层面监控磁盘空间大小，收到告警跑脚本去清理。
想请教一下，LTS本身有没有tracker的mysql记录清理机制，需要怎么配置。
谢谢~

**Comment by VincentGoph** [comment]
LTS内部是对记录有自动清理的LtsAdminDataCleaner，但是这种清理在大量写入删除之后还是会存在磁盘碎片化问题，可以将任务日志改为NoSQL存储，自动清理

**Comment by iamhaley** [comment]
NoSQL是一种选择，谢谢
